# Site info
domain: www.chriscooperjekyllstarter.com
title: Site GitHub Pages Jekyll Starter
author: Chris Cooper
email: chris@quixotic-chris.com

sass:
    sass_dir: _sass
    # Minification
#    style: compressed # for minification

exclude: 
    - README.md
    - Gemfile
    - Gemfile.lock
    - jekyll-install.sh
    - jekyll-serve.sh
    - jekyll-update.sh
