# Site info
domain: www.example.com
title: Site GitHub Pages Jekyll Starter
author: Your Name
email: your_email@email.com

sass:
    sass_dir: _sass
    # Minification
#    style: compressed # for minification

exclude: 
    - README.md
    - Gemfile
    - Gemfile.lock
    - jekyll-install.sh
    - jekyll-serve.sh
    - jekyll-update.sh
    - guides.txt
